spring.application.name=rag-pg

spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=test
spring.datasource.password=test
spring.ai.vectorstore.pgvector.initialize-schema=true

# Ollama config
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.timeout=5m
spring.ai.ollama.chat.options.model=tinyllama
spring.ai.ollama.embedding.options.model=nomic-embed-text
server.port=8086
